spring:
  redis:
    host: ${azaz.redis.host}
    port: ${azaz.redis.port}
    password: ${azaz.redis.password}
    database: ${azaz.redis.database}
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:10010"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes: # 网关路由配置
        - id: azaz-service-user
          uri: lb://azaz-service-user
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/azaz/user/**
logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info